<?php

namespace app\controllers;
use Yii;
use yii\web\NotFoundHttpException;
use yii\swiftmailer\Mailer;
use yii\web\Response;
use app\models\Product;
use app\models\Basket;
use app\models\Cart;
use PHPMailer;
class BasketController extends \yii\web\Controller
{
    public function beforeAction($action)
    {
        $basket=new Basket();
        if (count($basket->getBasket())<1){
            return $this->redirect(Yii::$app->homeUrl)->send();
        } else{
            return parent::beforeAction($action); // TODO: Change the autogenerated stub
        }
    }

    public function actionIndex()
    {
        $basket=new Basket();
        $products=$basket->findAll();
        $cart=$basket->getBasket();
        $summ=0;
        foreach ($products as $product){
            $summ=$summ+$cart[$product->id]*$product->price_1;
        }
        return $this->render('index',['products'=>$products, 'cart'=>$cart, 'itog'=>$summ]);
    }

    public function actionRemove(){
        if(is_numeric($id=Yii::$app->request->get("id"))){
            $basket=new Basket();
            $basket->removeBasket($id);
            return $this->redirect(['basket/index'])->send();
        } else{
            throw new NotFoundHttpException();
        }
    }

    public function actionUpdate(){
        $id=Yii::$app->request->get('id');
        $val=Yii::$app->request->get('val');
        if (is_numeric($id) && is_numeric($val)){
            $basket=new Basket();
            $basket->id=$id;
            $basket->count=$val;
            $basket->appendBasket();
            if($basket->save()){
                return $this->redirect(['basket/index']);
            }
        } else {
            throw new NotFoundHttpException();
        }
    }

    public function actionCart(){
        $model=new Cart();
        $basket=new Basket();
        $products=$basket->findAll();
        $cart=$basket->getBasket();
        $summ=0;
        foreach ($products as $product){
            $summ=$summ+$cart[$product->id]*$product->price_1;
        }
        if ($model->load(Yii::$app->request->post()) && $model->validate()){
            $model->save();
            $text_message="Заказ №".$model->id."<br>";
            $text_message.="Имя {$model->name}<br>";
            $text_message.="email {$model->email}<br>";
            $text_message.="Телефон {$model->phone}<br>";
            $text_message.="<table>";
            foreach ($products as $product){
                $text_message.="<tr>";
                $text_message.="<td>{$product->name}</td>";
                $text_message.="<td> артикул{$product->article}</td>";
                $text_message.="<td> кол-во{$cart[$product->id]}</td>";
                $itog=0;
                if ($summ<=8000){
                    $text_message.="<td> цена".$cart[$product->id]*$product->price_1."</td>";
                    $itog+=$cart[$product->id]*$product->price_1;
                } else if($summ>8000 and $summ<=15000){
                    $text_message.="<td> цена".$cart[$product->id]*$product->price_2."</td>";
                    $itog+=$cart[$product->id]*$product->price_2;
                } else if($summ>15000 and $summ<=30000){
                    $text_message.="<td> цена".$cart[$product->id]*$product->price_3."</td>";
                    $itog+=$cart[$product->id]*$product->price_3;
                } else{
                    $text_message.="<td> цена".$cart[$product->id]*$product->price_4."</td>";
                    $itog+=$cart[$product->id]*$product->price_4;
                }

                $text_message.="</tr>";
            }
            $text_message.="</table>";
            $text_message.="<br>Итог {$itog}";
            $mailer=new PHPMailer();
            $mailer->isSMTP();
            $mailer->Host="smtp-19.1gb.ru";
            $mailer->Port=465;
            $mailer->SMTPDebug=2;
            $mailer->SMTPAuth=true;
            $mailer->Username="u479196";
            $mailer->Password="39a1c85c4xv";
            $mailer->CharSet="UTF-8";
            $mailer->setFrom("info@proaksmarket.ru");
            $mailer->addAddress("proaksmarket@gmail.com");
            $mailer->addAddress($model->email);
            $mailer->isHTML(true);
            $mailer->Subject="Письмо с сайта proaksmarket";
            $mailer->Body=$text_message;
            if(!$mailer->send()){
                Yii::$app->session->set("qwe",$mailer->ErrorInfo);
            }
//            Yii::$app->mailer->compose()
//                ->setFrom("info@proaksmarket.ru")
//                ->setTo("proaksmarket@gmail.com")
//                ->setCc($model->email)
//                ->setSubject("Заказ")
//                ->setHtmlBody($text_message)
//                ->send();

            $basket->dropBasket();
            return $this->redirect(['site/apply'])->send();
        } else {
            return $this->render('cart',['itog'=>$summ, 'form'=>$model,'cart'=>json_encode($cart)]);
        }


    }

}
