<?php
/**
 * Created by PhpStorm.
 * User: deli13
 * Date: 03.09.17
 * Time: 21:44
 */

namespace app\models;
use Yii;
use yii\base\Model;
use app\models\Product;

class Basket extends Model
{
    private $basket;
    public $id;
    public $count;

    public function rules(){
        return [
            [['id','count'],'integer'],
        ]; // TODO: Change the autogenerated stub
    }
//Создание сессии
    public function init(){
        $session=Yii::$app->session;
        if(!$session->isActive){
            $session->open();
            $session->set('basket',[]);
        }
        $this->basket=$session->get('basket');
    }
//Добавление в корзину
    public function appendBasket(){
        if($this->validate()){
            $this->basket[$this->id]=$this->count;
        }
    }

    public function validate($attributeNames = null, $clearErrors = true){
        if (!is_numeric($this->id) or !is_numeric($this->count)){
            return false;
        }
        $product=Product::find()->where(['id'=>$this->id])->one();
        if(count($product)==0){
            return false;
        } else {
            return true;
        }
    }

    public function save(){
        Yii::$app->session->set('basket',$this->basket);
        return true;
    }
//Вывод всех товаров
    public function findAll(){
        if (count($this->basket)<1){
            return false;
        }
        $product=[];
        foreach ($this->basket as $key =>$value){
            $product[]=$key;
        }
        return Product::find()->where(['in','id',$product])->all();
    }

    public function getBasket(){
        return $this->basket;
    }
//Удаление из корзины
    public function removeBasket($id){
        if (is_numeric($id) && array_key_exists($id,$this->basket)){
            unset($this->basket[$id]);
            return $this->save();
        } else {
            return false;
        }
    }
    public function dropBasket(){
        Yii::$app->session->destroySession("basket");
        return true;
    }
}