<?php
/**
 * Created by PhpStorm.
 * User: deli13
 * Date: 03.09.17
 * Time: 21:44
 */

namespace app\models;
use Yii;
use yii\base\Model;
use app\models\Product;

class Basket extends Model
{
    private $basket;
    public $id;
    public $count;

    public function rules()
    {
        return [
            [['id','count'],'integer'],
        ]; // TODO: Change the autogenerated stub
    }
    public function init()
    {
        $session=Yii::$app->session;
        if(!$session->isActive){
            $session->open();
            $session->set('basket',[]);
        }
        $this->basket=$session->get('basket');
    }
    public function appendBasket(){
        if($this->validate()){
            $this->basket[$this->id]=$this->count;
        }
    }
    public function validate($attributeNames = null, $clearErrors = true)
    {
        if (!is_numeric($this->id) or !is_numeric($this->count)){
            return false;
        }
        $product=Product::find()->where(['id'=>$this->id])->one();
        if(count($product)==0){
            return false;
        } else {
            return true;
        }
    }
    public function save(){
        Yii::$app->session->set('basket',$this->basket);
        return true;
    }

}