<?php

namespace app\models;

use Yii;
//use yii\behaviors\SluggableBehavior;


/**
 * This is the model class for table "product".
 *
 * @property int $id
 * @property string $name
 * @property int $article
 * @property double $price_roznica
 * @property double $price_1
 * @property double $price_2
 * @property double $price_3
 * @property double $price_4
 * @property string $remain
 * @property string $created_at
 * @property string $updated_at
 * @property string $image
 * @property string $slug
 * @property int $id_catalog
 *
 * @property Catalog $catalog
 */
class Product extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        //return parent::behaviors(); // TODO: Change the autogenerated stub
        return [
            'slug' => [
                'class' => 'Zelenin\yii\behaviors\Slug',
                'slugAttribute' => 'slug',
                'attribute' => 'name',
                // optional params
                'ensureUnique' => true,
                'replacement' => '-',
                'lowercase' => true,
                'immutable' => false,
                // If intl extension is enabled, see http://userguide.icu-project.org/transforms/general.
                'transliterateOptions' => 'Russian-Latin/BGN; Any-Latin; Latin-ASCII; NFD; [:Nonspacing Mark:] Remove; NFC;'
            ]
        ];
    }

    public static function tableName()
    {
        return 'product';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'article', 'id_catalog'], 'required'],
            [['article', 'id_catalog'], 'integer'],
            [['price_roznica', 'price_1', 'price_2', 'price_3', 'price_4'], 'number'],
            [['created_at', 'updated_at'], 'safe'],
            [['name', 'slug'], 'string', 'max' => 2000],
            [['remain'], 'string', 'max' => 20],
            [['image'], 'string', 'max' => 100],
            [['id_catalog'], 'exist', 'skipOnError' => true, 'targetClass' => Catalog::className(), 'targetAttribute' => ['id_catalog' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'article' => 'Article',
            'price_roznica' => 'Price Roznica',
            'price_1' => 'Price 1',
            'price_2' => 'Price 2',
            'price_3' => 'Price 3',
            'price_4' => 'Price 4',
            'remain' => 'Remain',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'image' => 'Image',
            'slug' => 'Slug',
            'id_catalog' => 'Id Catalog',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCatalog()
    {
        return $this->hasOne(Catalog::className(), ['id' => 'id_catalog']);
    }

    /**
     * @inheritdoc
     * @return ProductQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new ProductQuery(get_called_class());
    }
}
